name: Backend API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend-api:
    runs-on: ubuntu-latest

    services:
      # Serviço do MongoDB
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: --health-cmd "mongo --eval 'db.runCommand(\"ping\").ok'" --health-interval 10s --health-timeout 5s --health-retries 5
      
      # Serviço do Redis
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Variáveis de ambiente necessárias para os testes
      MONGO_URI: mongodb://localhost:27017
      REDIS_URI: redis://localhost:6379
      SECRET_KEY: secretkey

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install backend-api dependencies
      working-directory: ./backend-api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: ./backend-api
      run: |
        pytest
