on:
  push:
    branches:
      - main  # Execute o workflow em pushes na branch 'main'
  pull_request:
    branches:
      - main  # Execute o workflow em pull requests para a branch 'main'

jobs:
  docker-image-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub      # Autenticação utilizando variáveis de ambiente pré-configuradas.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get short commit SHA    # Variável de tageamento automático baseado no SHA do commit.
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push frontend image   # Build frontend
        run: |
          docker build -t marciosbicigo/tcc-frontend:${{ env.COMMIT_SHA }} -f ./frontend/Dockerfile ./frontend
          docker push marciosbicigo/tcc-frontend:${{ env.COMMIT_SHA }}
          docker tag marciosbicigo/tcc-frontend:${{ env.COMMIT_SHA }} marciosbicigo/tcc-frontend:latest
          docker push marciosbicigo/tcc-frontend:latest

      - name: Build and push backend-api image   # Build backend
        run: |
          docker build -t marciosbicigo/tcc-backend-api:${{ env.COMMIT_SHA }} -f ./backend/Dockerfile ./backend
          docker push marciosbicigo/tcc-backend-api:${{ env.COMMIT_SHA }}
          docker tag marciosbicigo/tcc-backend-api:${{ env.COMMIT_SHA }} marciosbicigo/tcc-backend-api:latest
          docker push marciosbicigo/tcc-backend-api:latest