name: Frontend CI

on:
  push:
    branches:
      - main  # Execute o workflow em pushes na branch 'main'
  pull_request:
    branches:
      - main  # Execute o workflow em pull requests para a branch 'main'

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run frontend tests
      working-directory: ./frontend/app
      run: |
        pytest tests --maxfail=1 --disable-warnings
